In [1]:
import numpy as np
import numpy.matlib
from numpy.matlib import repmat
import math as m
import os
from scipy.linalg import toeplitz
from scipy.special import gamma
import scipy.sparse
import scipy
str=('dif1D.py')
p=os.system(str)
print(p)

1


In [109]:
ABC=np.mat([[-1 ,2],[2, 5],[1, 1]])
print(ABC)
x1=ABC[0,0:-1]
print(x1)
x2=ABC[1,0]
x3=ABC[2,0]
y1=ABC[0,1]
y2=ABC[1,1]
y3=ABC[2,1]
mr=(y2-y1)/(x2-x1)
mt=(y3-y2)/(x3-x2)
idf1 = np.isinf(mr)
idf2 = np.isinf(mt)
idf34 = mr==mt or np.isnan(mr) or np.isnan(mt)

# ============= Compute xc, the circle center x-coordinate
xc= (mr*mt*(y3-y1)+mr*(x2+x3)-mt*(x1+x2))/(2*(mr-mt))
if idf1==1: #Failure mode (1) ==> use limit case of mr==Inf
    xc=(mt*(y3-y1)+(x2+x3))/2 
if idf2==1: #Failure mode (2) ==> use limit case of mt==Inf
    xc = ((x1+x2)-mr*(y3-y1))/2; 
if idf34==1: #Failure mode (3) or (4) ==> cannot determine center point, return None
    xc = None
# ============= Compute yc, the circle center y-coordinate
yc=-1./mr*(xc-(x1+x2)/2)+(y1+y2)/2
idmr0 = mr==0
if idmr0==1: 
    yc = -1./mt*(xc-(x2+x3)/2)+(y2+y3)/2 
if idf34==1: #Failure mode (3) or (4) ==> cannot determine center point, return None
    yc = None
# ============= Compute the circle radius
R=m.sqrt((xc-x1)**2+(yc-y1)**2)
if idf34==1:
    R=float("inf")

xcyc=np.array([xc,yc]).reshape(2,1)

print(xcyc,R)

[[-1  2 -1  2]
 [ 2  5  2  5]
 [ 1  1  1  1]]
[[-1  2 -1]]


C:\Users\臧义程\AppData\Local\Temp\ipykernel_23592\2878443816.py:10: RuntimeWarning: divide by zero encountered in divide
  mr=(y2-y1)/(x2-x1)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

None


In [1]:
import numpy as np
from sklearn import svm

X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])

clt = svm.SVC(probability = True)
clt.fit(X, y)

print (clt.predict([[-0.8, -1]]))  # 输出为分类结果
print (clt.predict_proba([[-0.8, -1]]))  # 输出为概率值

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (378308358.py, line 10)